### PR TITLE
Few improvements.

### PR DESCRIPTION
**Pull request by 23rd**
Hey, @KuromeSan.
Do you accept pull requests for you program?

This one makes title a little bit nicer.
Removed `percent` from `100% percent free!` string.
And also after pressing the freedom button it becomes inactive, so that you can not start the freedom process several times.

### CODE REVIEW

**Comment by KuromeSan** [comment]
What's wrong with "100% percent free!"

**Comment by 23rd** [comment]
Well, the `percent` is already defined with `%`.
And the final phrase is `100 percent percent free`.

**Comment by KuromeSan** [comment]
Id rather just drop the "%" then tbh 
Or keep it for the lols it's trying to look like a script kiddie tool

**Comment by 23rd** [comment]
No problem. Updated.

**Pull request merged**
